### ISSUE TITLE
comparing the visualisations of the individual crime with the past crimes in the same category

### ISSUE THREAD

**Issue by davis67** [davis67/finalyrproject#5]

**Comment by bronejeffries** [comment]
how is this supposed to be done...i dont get it

**Comment by davis67** [comment]
Foreaxample compare bribery in 2018 with bribery in 2017 and briberyin 2016.Your goal is to dertemine the rate of change of an individual crime.

**Comment by davis67** [comment]
At the end, one can tell that an individual crime has increased or decreased depending on the crime changes

**Comment by bronejeffries** [comment]
done
